version: "2"
services:
  anaconda-nb:
    image: matthewcmead/anaconda-nb-docker-tensorflow-centos7
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ~/development/notebooks:/notebook
    command: jupyter-notebook --allow-root --notebook-dir=/notebook --ip="*"
